export const GET_ARTICLES_LOADING = "GET_ARTICLES_LOADING";

export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";

export const GET_ARTICLES_ERROR = "GET_ARTICLES_ERROR";

export const GET_ARTICLE_LOADING = "GET_ARTICLE_LOADING";

export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";

export const GET_ARTICLE_ERROR = "GET_ARTICLE_ERROR";

export const LIKE_ARTICLE_LOADING = "LIKE_ARTICLE_LOADING";

export const LIKE_ARTICLE_SUCCESS = "LIKE_ARTICLE_SUCCESS";

export const LIKE_ARTICLE_ERROR = "LIKE_ARTICLE_ERROR";

export const VIEW_ARTICLE_LOADING = "VIEW_ARTICLE_LOADING";

export const VIEW_ARTICLE_SUCCESS = "VIEW_ARTICLE_SUCCESS";

export const VIEW_ARTICLE_ERROR = "VIEW_ARTICLE_ERROR";

export const CHANGE_THEME = "CHANGE_THEME";

export const SET_INITIAL_STATE = "SET_INITIAL_STATE";
